services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
      MONGO_INITDB_DATABASE: mobileShop
    volumes:
      - ./db/data:/data/db
      - ./db/init-db.d:/docker-entrypoint-initdb.d:ro
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: examplepassword
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge
